import "./globals.css";
export const metadata = {
  title: 'データの視覚化',
  description: 'Generated by Next.js',
  icons: {
    icon: '/img/unikom.jpg',
  },
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  )
}
